Lanzamiento version 0.1.0
IslasGECI/ejemplo-rjags-clase1 pull request #1
Opened 2020-07-14 18:26 UTC by GenaroVel

## [Implementación en R](https://github.com/IslasGECI/manual#implementaci%C3%B3n-en-r)
- [ ] Corre una prueba dummy con testthat en GitHub Actions
- [ ] Evalúa cobertura con covr en GitHub Actions
- [ ] Realiza análisis estático (despeluza) con lintr en GitHub Actions
## Checklist adicional
- [ ] Verificar que se instala correctamente en [ejemplo-rjags-clase3](https://bitbucket.org/IslasGECI/ejemplo-rjags-clase3/)

2020-07-14 18:27 UTC, GenaroVel commented
Este PR no esta listo para ser revisado.

2020-07-14 19:30 UTC, nepito commented
Hola @GenaroVel no puedo verificar ninguno de los tres puntos de implementación porque no está el GitHub _actions_.
- [ ] Por favor agrega GitHub _actions_
- [ ] Agrega en la descripción del _pull request_ cómo  "Verificar que se instala correctamente en ejemplo-rjags-clase3"

2020-07-14 19:34 UTC, nepito requested changes
Hola @GenaroVel no puedo verificar ninguno de los tres puntos de implementación porque no está el GitHub _actions_.

2020-12-01 21:58 UTC, nepito commented
La cobertura todavía no funciona:
![image](https://user-images.githubusercontent.com/35377740/100801671-29fa7180-33dd-11eb-9b85-4911662583bf.png)
¿Será que la mejor menera de resolver esto sea instalando `git` desde `dockerfile`?

2021-01-12 20:28 UTC, nepito commented
Listo, ya quedó la versión v0.1.0

2021-01-12 20:29 UTC, nepito approved these changes
listones

2021-01-12 20:30 UTC, merged